---
title: "CMSC320 Final Project"
date: "5/19/2019"
name: "Shashwat Kapoor, Jin Ah Kang, Theresa Choi"
output: html_document
---

## Library

```{r setup, message=FALSE, warning=FALSE}
library(tidyr)
library(dplyr)
library(ggplot2)
library(tibble)
library(tidyverse)
library(askpass)
library(datasets)
library(leaflet)
library(KernSmooth)
library(sp)
```

### Working with Maps

```{r read_data}
dat <- read_csv("Japan_earthquakes.csv")

#tidying data
ext_dat <- dat[-c(7:13)] 
ext_dat <- ext_dat[c(1:7)]

ext_dat$copy <- ext_dat$time

ext_dat <- ext_dat %>%
  separate(copy, sep=" ", into = c("date", "time_in_sec")) %>%
  separate(date, sep="-", into = c("year", "month", "day")) %>%
  mutate(time=as.Date(time))

ext_dat
```

```{r season}

cp <- ext_dat
seasons <- cp %>% 
  mutate(spring = ifelse(month >= "03" & month <= "05", as.numeric(mag), NA)) %>% 
  mutate(summer = ifelse(month >= "06" & month <= "08", as.numeric(mag), NA)) %>% 
  mutate(fall = ifelse(month >= "09" & month <= "11", as.numeric(mag), NA)) %>% 
  mutate(winter = ifelse(month >= "12" | month <= "02", as.numeric(mag), NA)) %>%
  select(depth, spring, summer, fall, winter, mag)

season_df <- function(name) {
  filter(seasons, !is.na(seasons[name]))
}

corr_spring <- cor(season_df("spring")$depth,
                   season_df("spring")$spring)
corr_summer <- cor(season_df("summer")$depth,
                   season_df("summer")$summer)
corr_fall <- cor(season_df("fall")$depth,
                 season_df("fall")$fall)
corr_winter <- cor(season_df("winter")$depth,
                   season_df("winter")$winter)

```

```{r correlation}
#correlation between depth and magnitude
corr <- cor(ext_dat$depth, ext_dat$mag)

corr

#correlation, r = 0.0570), is less than 0.5, therefore, there is some form of correlation exist.
#next, look at it in the graph
```
```{r correlation plot}
attach(ext_dat)
  plot(mag, depth, main = "Correlation depth vs. magitude",
       xlab = "maginitude", ylab = "depth", pch = 20)
  
  #add linear line
abline(lm(depth~mag), col = "red")
```

```{r mark Japan for ref}
icons <- awesomeIcons(
  icon = 'fa-flag',
  library = 'fa',
)

#mark at tokyo
japan_map <- leaflet(ext_dat) %>%
  addTiles() %>%
  setView(lng = 139.80, lat = 35.68, zoom = 6) %>% #tokyo lat, lng
  addAwesomeMarkers(lng = 139.80, lat = 35.68, icon=icons)

japan_map
```

```{r}
winter <- ext_dat[ext_dat$month %in% c("01", "02", "12"), ]
spring <- ext_dat[ext_dat$month %in% c("03", "04", "05"), ]
summer <- ext_dat[ext_dat$month %in% c("06", "07", "08"), ]
autumn <- ext_dat[ext_dat$month %in% c("09", "10", "11"), ]

japan_map %>%
  addTiles() %>%
  setView(lng = 139.80, lat = 35.68, zoom = 4) %>%
  addCircleMarkers(data=winter, stroke = FALSE, radius = 3, color = "#0080FF", group = "winter") %>%
  addCircleMarkers(data=spring, stroke = FALSE, radius = 3, color = "#29AB87", group = "spring") %>%
  addCircleMarkers(data=summer, stroke = FALSE, radius = 3, color = "#999900", group = "summer") %>%
  addCircleMarkers(data=autumn, stroke = FALSE, radius = 3, color = "#EA3C53", group = "autumn") %>%
  addLayersControl(overlayGroups = c("winter", "spring", "summer", "autumn"),
                    options = layersControlOptions(collapsed = FALSE)) %>%
  hideGroup("spring") %>%
  hideGroup("summer") %>%
  hideGroup("autumn")
```

```{r}
X=cbind(ext_dat$longitude,ext_dat$latitude)
kde2d <- bkde2D(X, bandwidth=c(bw.ucv(X[,1]),bw.ucv(X[,2])))

x=kde2d$x1
y=kde2d$x2
z=kde2d$fhat
CL=contourLines(x , y , z)

quake_density <- japan_map %>%
  setView(lng = 139.80, lat = 35.68, zoom = 4)

for (x in seq(1, length(CL))) {
  quake_density <- quake_density %>%
  addPolylines(CL[[x]]$x, CL[[x]]$y, color = "#8B0000", weight = 2) %>%
  addPolygons(CL[[x]]$x, CL[[x]]$y, fillColor = "red", stroke = FALSE)
}

quake_density
```

TODO: 
1. correlation btwn depth and mag
2. hypothesis (mag sec1 = sec2 = sec3 = sec4)
3. ANOVA test to see the means of 'mb' 'mww' 'mwr' of mag are different
4. conclude with words
5. map to show the visual result to support our test 
